language: android
android:
  components:
  - tools
  - build-tools-25.0.2
  - android-25
  - android-21
  - add-on
  - extra
  - platform-tools
  - extra-google-googleplayservices
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-19
  - sys-img-armeabi-v7a-android-21
  licenses:
  - android-sdk-license-.+
  - ".+"
before_install:
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
env:
  global:
  - MALLOC_ARENA_MAX=2
sudo: required
before_script:
- echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a -s
  "768x1280"
- emulator -avd test -no-skin -no-audio -no-window &
- adb wait-for-device
- adb shell input keyevent 82 &
script: "./gradlew :app:build"
notifications:
  email:
    recipients:
    - csontos.valentin@gmail.com
    on_failure: always
deploy:
  provider: releases
  api_key:
    secure: LgI2gzNYgiSVu6h/9YwMspWsA8rYJ0PKOzQJw5LwYVGFJMvIxhn/01gQqt5GroPGIA8/t8doyQ7BmJi2ViQHEaPgK6uIqN349tLFxDpldc6ETsaj1hjStzkMUuaWK9g3xGisi5zqE9nAUqVY+N72FhCy4V19PgXH+woU4T1PQ5gdyIOrhxVOd4utRupCux5Jgl+Un+bPRJ5wQeY2diPd3w8ae1ovwSsonclMYzvUeWe0kJ5YVLV/DLgjNvCNTP8ANfoBKcMlhJbXVFn1ts0QE0Irk02k0dIrlfSmWOKxQhI1SoTU2KI8Numf3wOP1LUCHt7wte5D6RAV2+vKaNMFw4dMJcneNRgdE8Jhc47Bo7Sk0nc8+QYjMW51n2JRC+ilkQdRc7MqzvXBSw6OyPrbSruWVMMPFyaAfCegCVd7CZErRq2ZtBxlqlZD45sg1ratkSRmkOr/Oai24HpJHtGJGqjEDxpN3TO2cn25EOWGkJc2HkkqXu+ZewYGxa0RjNG5zem8HYSYvueTZy2CRQMxfJnqcztEj867gI4Do20uK+TNtdaGxSEdmVULyPlLhi4SJGV24ckUM0aZDUrVLin552Es8PG/qn0t8FUuUjneKl6UMRLgxqVD0hR1HUV0AwzqWDTa+SxrwlavNDruN7xorpNSUPrTRBs0PqIWUwz00Bs=
  file: app/build/outputs/apk/app*release*.apk
  file_glob: "true"
  skip_cleanup: true
  on:
    repo: vcsontos/Example2
    branch: develop
    tags: true
